spring.application.name=homeStyle

# PostgreSQL Database
spring.datasource.url=jdbc:postgresql://localhost:5432/postgres
spring.datasource.username=postgres
spring.datasource.password=raffo
spring.datasource.driver-class-name=org.postgresql.Driver

# JPA / Hibernate
# genera o aggiorna le tabelle automaticamente:
spring.jpa.hibernate.ddl-auto=update        
# mostra le query SQL nel log:
spring.jpa.show-sql=true                    
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

# Timezone
spring.jpa.properties.hibernate.jdbc.time_zone=UTC