server:
  port: 8080
  servlet:
    context-path: / # oppure /api se vuoi prefisso

spring:
  application:
    name: homestyle-backend

  datasource:
    url: jdbc:postgresql://localhost:5432/homestyle
    username: homestyle_user
    password: homestyle_password
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: none           # o update/create-drop a seconda dell'ambiente
    show-sql: true             # log SQL su console
    properties:
      hibernate:
        format_sql: true       # formatta le query nei log

  spring:
    security:
      oauth2:
        resourceserver:
          jwt:
            issuer-uri: http://localhost:8081/realms/homestyle


logging:
  level:
    root: INFO
    org.springframework.web: ERROR
    org.springframework.security: ERROR
    org.hibernate: ERROR
    com.homestyle.demo: DEBUG   # se vuoi tieni la tua app più verbosa

  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} %-5level [%thread] %logger{36} - %msg%n"
